version: "3.3"
services:

  webapp:
    container_name: vtracker
    image: app-builder:unknown
    ports:
      - 3000:3000
    volumes:
    - .:/opt/app/vtracker
    working_dir: /opt/app/vtracker
    command: ["yarn", "start"]